name = "username-palette"
compatibility_date = "2025-06-23"
account_id = "a8e8211c674c2b00f3a8996b65b56447"
workers_dev = true
main = ".output/server/index.mjs"
routes = [
  {pattern = "username-palette.mq1.dev", custom_domain = true}
]

[site]
bucket = ".output/public"

[build]
command = "pnpm run build:cf"

[observability.logs]
enabled = true

[placement]
mode = "smart"
