name = "username-palette"
type = "javascript"
compatibility_date = "2025-06-23"
account_id = "a8e8211c674c2b00f3a8996b65b56447"
workers_dev = true
routes = [
  {pattern = "username-palette.mq1.dev", custom_domain = true}
]
zone_id = ""

[site]
bucket = ".output/public"
entry-point = ".output/server/index.mjs"

[build]
command = "NITRO_PRESET=cloudflare pnpm nuxt build"
upload.format = "service-worker"

[observability.logs]
enabled = true

[placement]
mode = "smart"
